import { ComboboxItemGroup } from "@mantine/core";

export const data: ComboboxItemGroup[] = [
  {
    group: "Production",
    items: [
      { value: "1", label: "MEDILASER" },
      { value: "2", label: "GARZON" },
      { value: "4", label: "CIMA" },
      { value: "7", label: "HOMI" },
      { value: "8", label: "CL. SAN FRANSISCO" },
      { value: "11", label: "MEDICA NORTE" },
      { value: "12", label: "MEDICINA NUCLEAR" },
      { value: "13", label: "CDI" },
      { value: "16", label: "PRORAD" },
      { value: "17", label: "CENTRO DE CARDIOLOGÍA DIENIC" },
      { value: "24", label: "PANAMA DIAGNOSTIC CENTER" },
      { value: "30", label: "CASANARE" },
      { value: "31", label: "MEDIFACA" },
      { value: "32", label: "CLINICA NUEVA", disabled: true },
      { value: "33", label: "SAN JOSE", disabled: true },
      { value: "34", label: "INTEGRA - MARIACURI", disabled: true },
      { value: "36", label: "PROMED PAN" },
      { value: "38", label: "RADCO" },
      { value: "39", label: "BIOIMAGENES" },
      { value: "40", label: "SANTA MARIA" },
      { value: "45", label: "PROMED DEMO" },
      { value: "48", label: "CIMSA" },
      { value: "49", label: "UNIRAD" },
      { value: "78", label: "PITALITO" },
      { value: "80", label: "PROMED GUATEMALA" },
      { value: "81", label: "HOSPITAL MARIA INMACULADA" },
      { value: "82", label: "CLINICA ESPECIALIZADA DE AZUERO" },
      { value: "85", label: "CEDIM" },
    ],
  },
  {
    group: "QA",
    items: [
      { value: "9", label: "QA-MEDILASER" },
      { value: "10", label: "QA-CIMA" },
      { value: "15", label: "QA-GARZON" },
      { value: "50", label: "QA-HOMI" },
      { value: "51", label: "QA-CL. SAN FRANSISCO" },
      { value: "52", label: "QA-MEDICA NORTE" },
      { value: "53", label: "QA-MEDICINA NUCLEAR" },
      { value: "54", label: "QA-CDI" },
      { value: "55", label: "QA-INTEGRA - MARIACURI" },
      { value: "56", label: "QA-PORTAL IMAGENES MEDICAS" },
      { value: "57", label: "QA-PRORAD" },
      { value: "58", label: "QA-CENTRO DE CARDIOLOGÍA DIENIC" },
      { value: "59", label: "QA-PROMED PAN" },
      { value: "61", label: "QA-RADCO" },
      { value: "63", label: "QA-BIOIMAGENES" },
      { value: "64", label: "QA-SANTA MARIA" },
      { value: "65", label: "QA-PANAMA DIAGNOSTIC CENTER" },
      { value: "69", label: "QA-CASANARE" },
      { value: "70", label: "QA-MEDIFACA" },
      { value: "71", label: "QA-CLINICA NUEVA" },
      { value: "72", label: "QA-SAN JOSE" },
      { value: "76", label: "QA-CIMSA" },
      { value: "77", label: "QA-UNIRAD" },
      { value: "79", label: "QA-PITALITO" },
      { value: "86", label: "QA-CEDIM" },
    ],
  },
];

export const countries = [
  { value: "1", label: "COLOMBIA" },
  { value: "2", label: "COSTA RICA" },
  { value: "3", label: "MEXICO" },
  { value: "4", label: "PANAMA" },
  { value: "5", label: "GUATEMALA" },
  { value: "6", label: "HONDURAS" },
  { value: "7", label: "EL SALVADOR" },
  { value: "10", label: "ARGENTINA" },
  { value: "11", label: "BOLIVIA" },
  { value: "12", label: "BRAZIL" },
  { value: "13", label: "CANADA" },
  { value: "14", label: "CHILE" },
  { value: "15", label: "CUBA" },
  { value: "16", label: "REPUBLICA DOMINICANA" },
  { value: "17", label: "ECUADOR" },
  { value: "18", label: "PARAGUAY" },
  { value: "19", label: "PERU" },
  { value: "20", label: "PUERTO RICO" },
  { value: "21", label: "URUGUAY" },
  { value: "22", label: "VENEZUELA" },
  { value: "28", label: "ALEMANIA" },
  { value: "29", label: "TAIWAN" },
  { value: "30", label: "AFGHANISTAN" },
  { value: "31", label: "ALBANIA" },
  { value: "32", label: "ALGERIA" },
  { value: "33", label: "SAMOA AMERICANA" },
  { value: "34", label: "ANDORRA" },
  { value: "35", label: "ANGOLA" },
  { value: "36", label: "ANGUILLA" },
  { value: "37", label: "ANTARCTICA" },
  { value: "38", label: "ANTIGUA Y BARBUDA" },
  { value: "39", label: "ARMENIA" },
  { value: "40", label: "ARUBA" },
  { value: "41", label: "AUSTRALIA" },
  { value: "42", label: "AUSTRIA" },
  { value: "43", label: "AZERBAIJAN" },
  { value: "44", label: "BAHAMAS" },
  { value: "45", label: "BAHRAIN" },
  { value: "46", label: "BANGLADESH" },
  { value: "47", label: "BARBADOS" },
  { value: "48", label: "BELARUS" },
  { value: "49", label: "BELGIUM" },
  { value: "50", label: "BELIZE" },
  { value: "51", label: "BENIN" },
  { value: "52", label: "BERMUDA" },
  { value: "53", label: "BHUTAN" },
  { value: "54", label: "BONAIRE, SINT EUSTATIUS Y SABA" },
  { value: "55", label: "BOSNIA Y HERZEGOVINA" },
  { value: "56", label: "BOTSWANA" },
  { value: "57", label: "BOUVET ISLAND" },
  { value: "58", label: "BRITISH INDIAN OCEAN TERRITORY" },
  { value: "59", label: "ISLAS VIRGENES" },
  { value: "60", label: "BRUNEI DARUSSALAM" },
  { value: "61", label: "BULGARIA" },
  { value: "62", label: "BURKINA FASO" },
  { value: "63", label: "BURUNDI" },
  { value: "64", label: "CABO VERDE" },
  { value: "65", label: "CAMBODIA" },
  { value: "66", label: "CAMEROON" },
  { value: "67", label: "ISLAS CAYMAN" },
  { value: "68", label: "REPUBLICA CENTROAFRICANA" },
  { value: "69", label: "CHAD" },
  { value: "70", label: "CHINA" },
  { value: "71", label: "HONG KONG" },
  { value: "72", label: "MACAO" },
  { value: "73", label: "CHRISTMAS ISLAND" },
  { value: "74", label: "ISLAS COCOS" },
  { value: "75", label: "COMOROS" },
  { value: "76", label: "CONGO" },
  { value: "77", label: "ISLAS COOK" },
  { value: "78", label: "CROATIA" },
  { value: "79", label: "CURASAO" },
  { value: "80", label: "CYPRUS" },
  { value: "81", label: "CZECHIA" },
  { value: "82", label: "CATE D-IVOIRE" },
  { value: "83", label: "KOREA" },
  { value: "84", label: "CONGO" },
  { value: "85", label: "DENMARK" },
  { value: "86", label: "DJIBOUTI" },
  { value: "87", label: "DOMINICA" },
  { value: "88", label: "EGYPTO" },
  { value: "89", label: "GUINEA EQUATORIAL" },
  { value: "90", label: "ERITREA" },
  { value: "91", label: "ESTONIA" },
  { value: "92", label: "ESWATINI" },
  { value: "93", label: "ETHIOPIA" },
  { value: "94", label: "ISLAS MALVINAS" },
  { value: "95", label: "FAROE ISLANDS" },
  { value: "96", label: "FIJI" },
  { value: "97", label: "FINLAND" },
  { value: "98", label: "FRANCE" },
  { value: "99", label: "GUAYANA FRANCESA" },
  { value: "100", label: "POLINESIA FRANCESA" },
  { value: "101", label: "FRENCH SOUTHERN TERRITORIES" },
  { value: "102", label: "GABON" },
  { value: "103", label: "GAMBIA" },
  { value: "104", label: "GEORGIA" },
  { value: "105", label: "GHANA" },
  { value: "106", label: "GIBRALTAR" },
  { value: "107", label: "GREECE" },
  { value: "108", label: "GROENLANDIA" },
  { value: "109", label: "GRENADA" },
  { value: "110", label: "GUADELOUPE" },
  { value: "111", label: "GUAM" },
  { value: "112", label: "GUERNSEY" },
  { value: "113", label: "GUINEA" },
  { value: "114", label: "GUINEA-BISSAU" },
  { value: "115", label: "GUYANA" },
  { value: "116", label: "HAITI" },
  { value: "117", label: "ISLAS HEARD Y MCDONALD" },
  { value: "118", label: "HOLY SEE" },
  { value: "119", label: "HUNGARY" },
  { value: "120", label: "ISLANDIA" },
  { value: "121", label: "INDIA" },
  { value: "122", label: "INDONESIA" },
  { value: "123", label: "IRAN" },
  { value: "124", label: "IRAQ" },
  { value: "125", label: "IRELAND" },
  { value: "126", label: "ISLE OF MAN" },
  { value: "127", label: "ISRAEL" },
  { value: "128", label: "ITALY" },
  { value: "129", label: "JAMAICA" },
  { value: "130", label: "JAPAN" },
  { value: "131", label: "JERSEY" },
  { value: "132", label: "JORDAN" },
  { value: "133", label: "KAZAKHSTAN" },
  { value: "134", label: "KENYA" },
  { value: "135", label: "KIRIBATI" },
  { value: "136", label: "KIRGUISTAN" },
  { value: "137", label: "LAOS" },
  { value: "138", label: "LETONIA" },
  { value: "139", label: "LIECHTENSTEIN" },
  { value: "140", label: "LITUANIA" },
  { value: "141", label: "LUXEMBURGO" },
  { value: "142", label: "MACEDONIA DEL NORTE" },
  { value: "143", label: "MADAGASCAR" },
  { value: "144", label: "MALASIA" },
  { value: "145", label: "MALAWI" },
  { value: "146", label: "MALDIVAS" },
  { value: "147", label: "MALI" },
  { value: "148", label: "MALTA" },
  { value: "149", label: "ISLAS MARSHALL" },
  { value: "150", label: "MARTINICA" },
  { value: "151", label: "MAURICIO" },
  { value: "152", label: "MAURITANIA" },
  { value: "153", label: "MAYOTTE" },
  { value: "154", label: "MEXICO" },
  { value: "155", label: "MICRONESIA" },
  { value: "156", label: "MOLDAVIA" },
  { value: "157", label: "MONACO" },
  { value: "158", label: "MONGOLIA" },
  { value: "159", label: "MONTSERRAT" },
  { value: "160", label: "MONTENEGRO" },
  { value: "161", label: "MARRUECOS" },
  { value: "162", label: "MYANMAR" },
  { value: "163", label: "NAMIBIA" },
  { value: "164", label: "NAURU" },
  { value: "165", label: "NEPAL" },
  { value: "166", label: "NIGER" },
  { value: "167", label: "NIGERIA" },
  { value: "168", label: "NORFOLK ISLAND" },
  { value: "169", label: "NORUEGA" },
  { value: "170", label: "NUEVA CALEDONIA" },
  { value: "171", label: "NUEVA ZELANDA" },
  { value: "172", label: "OMÁN" },
  { value: "173", label: "PAKISTÁN" },
  { value: "174", label: "PALAU" },
  { value: "175", label: "PALESTINA" },
  { value: "176", label: "PANAMÁ" },
  { value: "177", label: "PAPUA NUEVA GUINEA" },
  { value: "178", label: "PARAGUAY" },
  { value: "179", label: "PERÚ" },
  { value: "180", label: "FILIPINAS" },
  { value: "181", label: "PORTUGAL" },
  { value: "182", label: "PUERTO RICO" },
  { value: "183", label: "REINO UNIDO" },
  { value: "184", label: "REPUBLICA CHECA" },
  { value: "185", label: "REPUBLICA DOMINICANA" },
  { value: "186", label: "REPUBLICA DEL CONGO" },
  { value: "187", label: "RUMANÍA" },
  { value: "188", label: "RUSIA" },
  { value: "189", label: "RUIDA" },
  { value: "190", label: "SABAH" },
  { value: "191", label: "SAHARA OCCIDENTAL" },
  { value: "192", label: "SANTA HELENA" },
  { value: "193", label: "SANTA LUCÍA" },
  { value: "194", label: "SENEGAL" },
  { value: "195", label: "SERBIA" },
  { value: "196", label: "SINGAPUR" },
  { value: "197", label: "SIRIA" },
  { value: "198", label: "SOMALIA" },
  { value: "199", label: "SUDÁN" },
  { value: "200", label: "SUDÁN DEL SUR" },
  { value: "201", label: "SUECIA" },
  { value: "202", label: "SUIZA" },
  { value: "203", label: "SURINAME" },
  { value: "204", label: "TAILANDIA" },
  { value: "205", label: "TANZANIA" },
  { value: "206", label: "TAYIKISTÁN" },
  { value: "207", label: "TERRITORIOS BRITÁNICOS DEL OCÉANO ÍNDICO" },
  { value: "208", label: "TIMOR ORIENTAL" },
  { value: "209", label: "TONGA" },
  { value: "210", label: "TRINIDAD Y TOBAGO" },
  { value: "211", label: "TURKMENISTÁN" },
  { value: "212", label: "TURQUÍA" },
  { value: "213", label: "TUVALU" },
  { value: "214", label: "UCRANIA" },
  { value: "215", label: "UGANDA" },
  { value: "216", label: "UNIÓN EUROPEA" },
  { value: "217", label: "UNIÓN SOVIÉTICA" },
  { value: "218", label: "VANUATU" },
  { value: "219", label: "VENEZUELA" },
  { value: "220", label: "VIETNAM" },
  { value: "221", label: "WALLIS Y FUTUNA" },
  { value: "222", label: "YEMEN" },
  { value: "223", label: "ZAMBIA" },
  { value: "224", label: "ZIMBABUE" },
];

export const typeDocument = [
  { value: "1", label: "Cedula" },
  { value: "2", label: "Cedula" },
  { value: "3", label: "INE" },
  { value: "4", label: "Cedula" },
  { value: "5", label: "Cedula de Extranjería" },
  { value: "6", label: "Pasaporte" },
  { value: "7", label: "Cedula de Extranjería" },
  { value: "8", label: "Pasaporte" },
  { value: "9", label: "Cédula" },
  { value: "10", label: "DUI" },
  { value: "11", label: "Cédula" },
  { value: "12", label: "Cedula de Extranjeria" },
];
