import { ComboboxItemGroup } from "@mantine/core";

export const data: ComboboxItemGroup[] = [
  {
    group: "Production",
    items: [
      { value: "1", label: "MEDILASER" },
      { value: "2", label: "GARZON" },
      { value: "4", label: "CIMA" },
      { value: "7", label: "HOMI" },
      { value: "8", label: "CL. SAN FRANSISCO" },
      { value: "11", label: "MEDICA NORTE" },
      { value: "12", label: "MEDICINA NUCLEAR" },
      { value: "13", label: "CDI" },
      { value: "16", label: "PRORAD" },
      { value: "17", label: "CENTRO DE CARDIOLOGÍA DIENIC" },
      { value: "24", label: "PANAMA DIAGNOSTIC CENTER" },
      { value: "30", label: "CASANARE" },
      { value: "31", label: "MEDIFACA" },
      { value: "32", label: "CLINICA NUEVA", disabled: true },
      { value: "33", label: "SAN JOSE", disabled: true },
      { value: "34", label: "INTEGRA - MARIACURI", disabled: true },
      { value: "36", label: "PROMED PAN" },
      { value: "38", label: "RADCO" },
      { value: "39", label: "BIOIMAGENES" },
      { value: "40", label: "SANTA MARIA" },
      { value: "45", label: "PROMED DEMO" },
      { value: "48", label: "CIMSA" },
      { value: "49", label: "UNIRAD" },
      { value: "78", label: "PITALITO" },
      { value: "80", label: "PROMED GUATEMALA" },
      { value: "81", label: "HOSPITAL MARIA INMACULADA" },
      { value: "82", label: "CLINICA ESPECIALIZADA DE AZUERO" },
      { value: "85", label: "CEDIM" },
    ],
  },
  {
    group: "QA",
    items: [
      { value: "9", label: "QA-MEDILASER" },
      { value: "10", label: "QA-CIMA" },
      { value: "15", label: "QA-GARZON" },
      { value: "50", label: "QA-HOMI" },
      { value: "51", label: "QA-CL. SAN FRANSISCO" },
      { value: "52", label: "QA-MEDICA NORTE" },
      { value: "53", label: "QA-MEDICINA NUCLEAR" },
      { value: "54", label: "QA-CDI" },
      { value: "55", label: "QA-INTEGRA - MARIACURI" },
      { value: "56", label: "QA-PORTAL IMAGENES MEDICAS" },
      { value: "57", label: "QA-PRORAD" },
      { value: "58", label: "QA-CENTRO DE CARDIOLOGÍA DIENIC" },
      { value: "59", label: "QA-PROMED PAN" },
      { value: "61", label: "QA-RADCO" },
      { value: "63", label: "QA-BIOIMAGENES" },
      { value: "64", label: "QA-SANTA MARIA" },
      { value: "65", label: "QA-PANAMA DIAGNOSTIC CENTER" },
      { value: "69", label: "QA-CASANARE" },
      { value: "70", label: "QA-MEDIFACA" },
      { value: "71", label: "QA-CLINICA NUEVA" },
      { value: "72", label: "QA-SAN JOSE" },
      { value: "76", label: "QA-CIMSA" },
      { value: "77", label: "QA-UNIRAD" },
      { value: "79", label: "QA-PITALITO" },
      { value: "86", label: "QA-CEDIM" },
    ],
  },
];

export const typeDocument = [
  { value: "1", label: "CC" },
  { value: "2", label: "TI" },
  { value: "3", label: "CE" },
  { value: "4", label: "NIT" },
];
